"""Initial seed for HackTrack — hiring hackathons, conferences, summits,
invite-only events, meetups & workshops for STUDENTS and WORKING PROFESSIONALS."""
from datetime import datetime, timezone, timedelta


def _future(days):
    return (datetime.utcnow() + timedelta(days=days)).replace(tzinfo=timezone.utc).isoformat()


# event_type: Hackathon | Conference | Summit | Workshop | Meetup | Invite-only
# audience: subset of [Students, Professionals]
SEED_HACKATHONS = [
    # ---------- Hiring Hackathons (students) ----------
    {
        "title": "HackerRamp: WeForShe", "company": "Myntra",
        "company_logo": "https://logo.clearbit.com/myntra.com",
        "event_type": "Hackathon", "audience": ["Students"],
        "region": "India", "mode": "Hybrid", "status": "Upcoming",
        "tags": ["Women only", "Hiring", "Tech"],
        "start_date": _future(25), "end_date": _future(55),
        "registration_deadline": _future(20),
        "registration_link": "https://www.myntra.com/hackerramp",
        "location": "Bengaluru + Online",
        "description": "Myntra's flagship women-only hiring hackathon for SDE & PM roles. Build retail-tech & win a PPO.",
        "eligibility": "Women in pre-final / final year of B.E./B.Tech/M.Tech/MS-CS.",
        "prizes": "PPO + INR 5L cash + mentorship.",
        "source_url": "https://www.myntra.com/hackerramp",
        "prep": None,
    },
    {
        "title": "Meesho Maverix", "company": "Meesho",
        "company_logo": "https://logo.clearbit.com/meesho.com",
        "event_type": "Hackathon", "audience": ["Students"],
        "region": "India", "mode": "Online", "status": "Open",
        "tags": ["SDE", "Hiring", "Coding"],
        "start_date": _future(7), "end_date": _future(14),
        "registration_deadline": _future(5),
        "registration_link": "https://www.meesho.io/maverix",
        "location": "Online (India)",
        "description": "Meesho's premier hiring challenge for SDE-1 roles. 3 coding rounds + system design + culture round.",
        "eligibility": "2025/2026 graduating batch, CS/IT majors.",
        "prizes": "Full-time SDE-1 offer + INR 1L cash.",
        "source_url": "https://www.meesho.io/careers", "prep": None,
    },
    {
        "title": "Flipkart Runway", "company": "Flipkart",
        "company_logo": "https://logo.clearbit.com/flipkart.com",
        "event_type": "Hackathon", "audience": ["Students"],
        "region": "India", "mode": "Online", "status": "Upcoming",
        "tags": ["Women only", "SDE", "Hiring"],
        "start_date": _future(40), "end_date": _future(75),
        "registration_deadline": _future(35),
        "registration_link": "https://flipkartrunway.in",
        "location": "Online + Bengaluru finals",
        "description": "Flipkart's flagship women-in-tech hiring program. Coding, design and pitch rounds.",
        "eligibility": "Women in pre-final / final year of engineering.",
        "prizes": "PPO + INR 3L cash + mentorship.",
        "source_url": "https://flipkartrunway.in", "prep": None,
    },
    {
        "title": "Amazon HackOn", "company": "Amazon",
        "company_logo": "https://logo.clearbit.com/amazon.com",
        "event_type": "Hackathon", "audience": ["Students"],
        "region": "India", "mode": "Hybrid", "status": "Upcoming",
        "tags": ["Hiring", "ML", "Cloud"],
        "start_date": _future(30), "end_date": _future(45),
        "registration_deadline": _future(25),
        "registration_link": "https://amazonhackon.com",
        "location": "Online + Bengaluru/Hyderabad finals",
        "description": "Amazon India's flagship hiring hackathon across ML, Cloud, Mobile and AWS tracks.",
        "eligibility": "Engineering students graduating in 2025/2026.",
        "prizes": "PPO + INR 3L grand prize per track.",
        "source_url": "https://amazonhackon.com", "prep": None,
    },
    {
        "title": "Microsoft Engage", "company": "Microsoft",
        "company_logo": "https://logo.clearbit.com/microsoft.com",
        "event_type": "Hackathon", "audience": ["Students"],
        "region": "India", "mode": "Online", "status": "Upcoming",
        "tags": ["Mentorship", "Hiring", "Project"],
        "start_date": _future(45), "end_date": _future(90),
        "registration_deadline": _future(40),
        "registration_link": "https://microsoft.acehacker.com/engage",
        "location": "Online (India)",
        "description": "4-week mentorship program by Microsoft engineers. Top performers get internship + PPO interviews.",
        "eligibility": "Pre-final year engineering students (India).",
        "prizes": "Microsoft Internship + PPO fast-track.",
        "source_url": "https://microsoft.acehacker.com/engage", "prep": None,
    },
    {
        "title": "Razorpay FTX", "company": "Razorpay",
        "company_logo": "https://logo.clearbit.com/razorpay.com",
        "event_type": "Hackathon", "audience": ["Students"],
        "region": "India", "mode": "Online", "status": "Open",
        "tags": ["Hiring", "Fintech", "SDE"],
        "start_date": _future(3), "end_date": _future(17),
        "registration_deadline": _future(2),
        "registration_link": "https://razorpay.com/ftx",
        "location": "Online (India)",
        "description": "Razorpay's premier full-time hiring exam for SDE roles. 3-stage coding + system design.",
        "eligibility": "Graduating in 2025/26, CS/IT/ECE.",
        "prizes": "Razorpay SDE-1 offer + INR 1L bonus.",
        "source_url": "https://razorpay.com/jobs", "prep": None,
    },
    {
        "title": "Google Hash Code", "company": "Google",
        "company_logo": "https://logo.clearbit.com/google.com",
        "event_type": "Hackathon", "audience": ["Students", "Professionals"],
        "region": "International", "mode": "Online", "status": "Upcoming",
        "tags": ["Algorithms", "Team", "Global"],
        "start_date": _future(60), "end_date": _future(62),
        "registration_deadline": _future(55),
        "registration_link": "https://codingcompetitions.withgoogle.com/hashcode",
        "location": "Online (Global)",
        "description": "Google's team programming competition. Solve a real engineering problem in 4 hours with your team.",
        "eligibility": "Anyone 18+, teams of 2-4.",
        "prizes": "Google swag, interview fast-track, World Finals trip.",
        "source_url": "https://codingcompetitions.withgoogle.com", "prep": None,
    },
    {
        "title": "Meta Hacker Cup", "company": "Meta",
        "company_logo": "https://logo.clearbit.com/meta.com",
        "event_type": "Hackathon", "audience": ["Students", "Professionals"],
        "region": "International", "mode": "Online", "status": "Upcoming",
        "tags": ["Competitive Programming", "Hiring"],
        "start_date": _future(70), "end_date": _future(75),
        "registration_deadline": _future(65),
        "registration_link": "https://www.facebook.com/codingcompetitions/hacker-cup",
        "location": "Online (Global)",
        "description": "Meta's annual algorithmic programming contest. Top performers get fast-tracked interviews.",
        "eligibility": "Anyone 18+.",
        "prizes": "USD 20,000 grand prize + Meta interview pipeline.",
        "source_url": "https://www.facebook.com/codingcompetitions", "prep": None,
    },

    # ---------- Conferences (professionals) ----------
    {
        "title": "AWS re:Invent 2026", "company": "Amazon Web Services",
        "company_logo": "https://logo.clearbit.com/aws.amazon.com",
        "event_type": "Conference", "audience": ["Professionals"],
        "region": "International", "mode": "Offline", "status": "Upcoming",
        "tags": ["Cloud", "DevOps", "AI"],
        "start_date": _future(110), "end_date": _future(115),
        "registration_deadline": _future(95),
        "registration_link": "https://reinvent.awsevents.com",
        "location": "Las Vegas, USA",
        "description": "AWS's flagship cloud conference. 2000+ sessions across infra, AI/ML, security and developer tools.",
        "eligibility": "Open to engineers, architects, founders (paid pass).",
        "prizes": "Hands-on labs, certifications, swag, recruiter access.",
        "source_url": "https://reinvent.awsevents.com", "prep": None,
    },
    {
        "title": "Google I/O 2026", "company": "Google",
        "company_logo": "https://logo.clearbit.com/google.com",
        "event_type": "Conference", "audience": ["Students", "Professionals"],
        "region": "International", "mode": "Hybrid", "status": "Upcoming",
        "tags": ["Android", "AI", "Cloud", "Web"],
        "start_date": _future(70), "end_date": _future(72),
        "registration_deadline": _future(60),
        "registration_link": "https://io.google",
        "location": "Mountain View, CA + Online",
        "description": "Google's annual developer conference. Keynotes on Gemini, Android, Pixel, Cloud + 200+ technical sessions.",
        "eligibility": "Free virtual; in-person via lottery for active devs.",
        "prizes": "Networking, early API access, swag.",
        "source_url": "https://io.google", "prep": None,
    },
    {
        "title": "KubeCon + CloudNativeCon EU 2026", "company": "CNCF",
        "company_logo": "https://logo.clearbit.com/cncf.io",
        "event_type": "Conference", "audience": ["Professionals"],
        "region": "International", "mode": "Offline", "status": "Upcoming",
        "tags": ["Kubernetes", "Cloud Native", "DevOps"],
        "start_date": _future(85), "end_date": _future(88),
        "registration_deadline": _future(75),
        "registration_link": "https://events.linuxfoundation.org/kubecon-cloudnativecon-europe",
        "location": "Amsterdam, NL",
        "description": "The premier Kubernetes + cloud-native conference. Talks, workshops and end-user case studies.",
        "eligibility": "Open (paid pass + scholarships available).",
        "prizes": "Networking with maintainers, hiring booths, hands-on labs.",
        "source_url": "https://events.linuxfoundation.org", "prep": None,
    },
    {
        "title": "PyCon India 2026", "company": "Python Software Foundation",
        "company_logo": "https://logo.clearbit.com/python.org",
        "event_type": "Conference", "audience": ["Students", "Professionals"],
        "region": "India", "mode": "Hybrid", "status": "Upcoming",
        "tags": ["Python", "Open Source", "Community"],
        "start_date": _future(100), "end_date": _future(103),
        "registration_deadline": _future(85),
        "registration_link": "https://in.pycon.org",
        "location": "Hyderabad + Online",
        "description": "India's largest Python conference — talks, workshops, dev sprints and hiring stalls.",
        "eligibility": "Open to all.",
        "prizes": "Networking, OSS sprints, recruiter expo.",
        "source_url": "https://in.pycon.org", "prep": None,
    },

    # ---------- Summits ----------
    {
        "title": "GitHub Universe 2026", "company": "GitHub",
        "company_logo": "https://logo.clearbit.com/github.com",
        "event_type": "Summit", "audience": ["Students", "Professionals"],
        "region": "International", "mode": "Hybrid", "status": "Open",
        "tags": ["OSS", "DevTools", "Copilot"],
        "start_date": _future(0), "end_date": _future(2),
        "registration_deadline": _future(12),
        "registration_link": "https://githubuniverse.com",
        "location": "San Francisco + Online",
        "description": "GitHub's flagship dev summit. Copilot, Actions, Codespaces deep-dives plus the annual hackathon.",
        "eligibility": "Anyone 18+ with a GitHub account.",
        "prizes": "USD 10,000 hackathon prize + interview fast-track.",
        "source_url": "https://githubuniverse.com", "prep": None,
    },
    {
        "title": "NVIDIA GTC 2026", "company": "NVIDIA",
        "company_logo": "https://logo.clearbit.com/nvidia.com",
        "event_type": "Summit", "audience": ["Professionals"],
        "region": "International", "mode": "Hybrid", "status": "Upcoming",
        "tags": ["AI", "GPU", "Research"],
        "start_date": _future(50), "end_date": _future(53),
        "registration_deadline": _future(40),
        "registration_link": "https://www.nvidia.com/gtc",
        "location": "San Jose, CA + Online",
        "description": "NVIDIA's AI developer summit — keynotes on LLMs, robotics, autonomous systems and Blackwell.",
        "eligibility": "Open (free virtual / paid in-person).",
        "prizes": "Networking with NVIDIA research, hands-on AI labs.",
        "source_url": "https://www.nvidia.com/gtc", "prep": None,
    },

    # ---------- Invite-only / fellowships ----------
    {
        "title": "Y Combinator Startup School", "company": "Y Combinator",
        "company_logo": "https://logo.clearbit.com/ycombinator.com",
        "event_type": "Invite-only", "audience": ["Students", "Professionals"],
        "region": "International", "mode": "Online", "status": "Open",
        "tags": ["Startup", "Founder", "Cohort"],
        "start_date": _future(5), "end_date": _future(70),
        "registration_deadline": _future(4),
        "registration_link": "https://www.startupschool.org",
        "location": "Online (Global)",
        "description": "A 10-week online course for founders building real startups. Cohort-based with YC mentorship.",
        "eligibility": "Anyone working on or planning a startup.",
        "prizes": "YC mentorship, Bookface community access, Demo Day.",
        "source_url": "https://www.startupschool.org", "prep": None,
    },
    {
        "title": "Stripe Sessions 2026", "company": "Stripe",
        "company_logo": "https://logo.clearbit.com/stripe.com",
        "event_type": "Invite-only", "audience": ["Professionals"],
        "region": "International", "mode": "Offline", "status": "Upcoming",
        "tags": ["Fintech", "Founder", "Product"],
        "start_date": _future(65), "end_date": _future(66),
        "registration_deadline": _future(50),
        "registration_link": "https://stripe.com/sessions",
        "location": "San Francisco, USA",
        "description": "Stripe's invite-only customer & founder summit. Product launches, founder fireside chats.",
        "eligibility": "Active Stripe customers, founders, partners (invite or apply).",
        "prizes": "Networking, early access to new APIs.",
        "source_url": "https://stripe.com/sessions", "prep": None,
    },

    # ---------- Workshops / bootcamps ----------
    {
        "title": "Google Cloud Skills Boost Live", "company": "Google Cloud",
        "company_logo": "https://logo.clearbit.com/cloud.google.com",
        "event_type": "Workshop", "audience": ["Students", "Professionals"],
        "region": "International", "mode": "Online", "status": "Open",
        "tags": ["Cloud", "Certification", "Hands-on"],
        "start_date": _future(1), "end_date": _future(30),
        "registration_deadline": _future(0),
        "registration_link": "https://cloud.google.com/training",
        "location": "Online (Global)",
        "description": "Self-paced hands-on labs & live workshops leading to Google Cloud certifications.",
        "eligibility": "Anyone with a Google account.",
        "prizes": "GCP certification voucher discounts + skill badges.",
        "source_url": "https://cloud.google.com/training", "prep": None,
    },
    {
        "title": "Atlassian Team '26", "company": "Atlassian",
        "company_logo": "https://logo.clearbit.com/atlassian.com",
        "event_type": "Conference", "audience": ["Professionals"],
        "region": "International", "mode": "Hybrid", "status": "Upcoming",
        "tags": ["Agile", "Productivity", "Enterprise"],
        "start_date": _future(80), "end_date": _future(82),
        "registration_deadline": _future(70),
        "registration_link": "https://www.atlassian.com/company/events/team",
        "location": "Anaheim, CA + Online",
        "description": "Atlassian's annual conference on teamwork, agile and dev productivity.",
        "eligibility": "Engineering managers, devs, product folk.",
        "prizes": "Networking, hands-on Jira/Confluence labs.",
        "source_url": "https://www.atlassian.com/company/events/team", "prep": None,
    },

    # ---------- Meetups ----------
    {
        "title": "Bangalore Backend Devs Meetup", "company": "Backend India",
        "company_logo": "https://logo.clearbit.com/meetup.com",
        "event_type": "Meetup", "audience": ["Professionals"],
        "region": "India", "mode": "Offline", "status": "Open",
        "tags": ["Backend", "Networking", "Talks"],
        "start_date": _future(4), "end_date": _future(4),
        "registration_deadline": _future(3),
        "registration_link": "https://www.meetup.com/bangalore-backend-devs",
        "location": "Bengaluru (Indiranagar)",
        "description": "Monthly meetup of senior backend engineers — lightning talks on scaling, architecture, war stories.",
        "eligibility": "Working backend engineers (2+ yrs).",
        "prizes": "Networking, pizza, free swag.",
        "source_url": "https://www.meetup.com/bangalore-backend-devs", "prep": None,
    },
    {
        "title": "Product Tank Mumbai", "company": "Mind the Product",
        "company_logo": "https://logo.clearbit.com/mindtheproduct.com",
        "event_type": "Meetup", "audience": ["Professionals"],
        "region": "India", "mode": "Offline", "status": "Open",
        "tags": ["Product", "PM", "Networking"],
        "start_date": _future(6), "end_date": _future(6),
        "registration_deadline": _future(5),
        "registration_link": "https://www.mindtheproduct.com/producttank",
        "location": "Mumbai (BKC)",
        "description": "Monthly PM meetup with talks from senior product leaders in Indian unicorns.",
        "eligibility": "Working PMs, aspiring PMs.",
        "prizes": "Networking, free entry, recruiter mingle.",
        "source_url": "https://www.mindtheproduct.com/producttank", "prep": None,
    },

    # ---------- More hiring (professionals) ----------
    {
        "title": "Cred Mint Hiring Challenge", "company": "Cred",
        "company_logo": "https://logo.clearbit.com/cred.club",
        "event_type": "Hackathon", "audience": ["Professionals"],
        "region": "India", "mode": "Online", "status": "Open",
        "tags": ["Hiring", "SDE-2/3", "Fintech"],
        "start_date": _future(2), "end_date": _future(9),
        "registration_deadline": _future(1),
        "registration_link": "https://careers.cred.club",
        "location": "Online (India)",
        "description": "Cred's senior engineer hiring challenge — system design + advanced DSA + architecture interview.",
        "eligibility": "Working engineers with 3+ years of experience.",
        "prizes": "Cred SDE-2/3 offer with relocation to Bengaluru.",
        "source_url": "https://careers.cred.club", "prep": None,
    },
    {
        "title": "Stripe Engineering Sprint", "company": "Stripe",
        "company_logo": "https://logo.clearbit.com/stripe.com",
        "event_type": "Hackathon", "audience": ["Professionals"],
        "region": "International", "mode": "Online", "status": "Upcoming",
        "tags": ["Hiring", "Backend", "Payments"],
        "start_date": _future(20), "end_date": _future(27),
        "registration_deadline": _future(17),
        "registration_link": "https://stripe.com/jobs/engineering",
        "location": "Online (Global)",
        "description": "Stripe's 1-week paid sprint with the engineering team — real PRs, no whiteboard rounds. Offer at the end if you ship.",
        "eligibility": "Working engineers, 2+ years exp in distributed systems.",
        "prizes": "Stripe engineering offer + paid sprint stipend.",
        "source_url": "https://stripe.com/jobs", "prep": None,
    },
]
