"""Initial seed hackathons / hiring challenges so the app is useful immediately.
The AI refresh endpoint augments / refreshes this list with Gemini."""
from datetime import datetime, timezone, timedelta


def _iso(d):
    return d.replace(tzinfo=timezone.utc).isoformat()


def _future(days):
    return _iso(datetime.utcnow() + timedelta(days=days))


SEED_HACKATHONS = [
    {
        "title": "HackerRamp: WeForShe",
        "company": "Myntra",
        "company_logo": "https://logo.clearbit.com/myntra.com",
        "region": "India",
        "mode": "Hybrid",
        "status": "Upcoming",
        "tags": ["Women only", "Tech", "Hiring"],
        "start_date": _future(25),
        "end_date": _future(55),
        "registration_deadline": _future(20),
        "registration_link": "https://www.myntra.com/hackerramp",
        "location": "Bengaluru + Online",
        "description": "Myntra's flagship women-only hiring hackathon for engineering & product roles. Build retail-tech solutions and win an SDE / PM offer.",
        "eligibility": "Women in pre-final / final year of B.E./B.Tech/M.Tech or Master's CS.",
        "prizes": "Pre-placement offers, cash prizes up to INR 5L, mentorship.",
        "source_url": "https://www.myntra.com/hackerramp",
        "prep": None,
    },
    {
        "title": "Meesho Maverix",
        "company": "Meesho",
        "company_logo": "https://logo.clearbit.com/meesho.com",
        "region": "India",
        "mode": "Online",
        "status": "Open",
        "tags": ["SDE", "Hiring", "Coding"],
        "start_date": _future(7),
        "end_date": _future(14),
        "registration_deadline": _future(5),
        "registration_link": "https://www.meesho.io/maverix",
        "location": "Online (India)",
        "description": "Meesho's premier hiring challenge for SDE-1 roles. 3 coding rounds + system design + culture round.",
        "eligibility": "2024 / 2025 graduating batch, CS / IT majors.",
        "prizes": "Full-time SDE-1 offer + INR 1L cash prize for top 3.",
        "source_url": "https://www.meesho.io/careers",
        "prep": None,
    },
    {
        "title": "Flipkart Runway",
        "company": "Flipkart",
        "company_logo": "https://logo.clearbit.com/flipkart.com",
        "region": "India",
        "mode": "Online",
        "status": "Upcoming",
        "tags": ["Women only", "SDE", "Hiring"],
        "start_date": _future(40),
        "end_date": _future(75),
        "registration_deadline": _future(35),
        "registration_link": "https://flipkartrunway.in",
        "location": "Online + Bengaluru finals",
        "description": "Flipkart's flagship women-in-tech hiring program. Coding, design and pitch rounds.",
        "eligibility": "Women in pre-final / final year of engineering.",
        "prizes": "PPO at Flipkart, INR 3L cash, mentorship.",
        "source_url": "https://flipkartrunway.in",
        "prep": None,
    },
    {
        "title": "Google Hash Code",
        "company": "Google",
        "company_logo": "https://logo.clearbit.com/google.com",
        "region": "International",
        "mode": "Online",
        "status": "Upcoming",
        "tags": ["Algorithms", "Team", "Global"],
        "start_date": _future(60),
        "end_date": _future(62),
        "registration_deadline": _future(55),
        "registration_link": "https://codingcompetitions.withgoogle.com/hashcode",
        "location": "Online (Global)",
        "description": "Google's team programming competition. Solve a real engineering problem in 4 hours with your team.",
        "eligibility": "Anyone 18+, teams of 2-4.",
        "prizes": "Google swag, interview fast-track, World Finals trip.",
        "source_url": "https://codingcompetitions.withgoogle.com",
        "prep": None,
    },
    {
        "title": "Meta Hacker Cup",
        "company": "Meta",
        "company_logo": "https://logo.clearbit.com/meta.com",
        "region": "International",
        "mode": "Online",
        "status": "Upcoming",
        "tags": ["Competitive Programming", "Hiring"],
        "start_date": _future(70),
        "end_date": _future(75),
        "registration_deadline": _future(65),
        "registration_link": "https://www.facebook.com/codingcompetitions/hacker-cup",
        "location": "Online (Global)",
        "description": "Meta's annual algorithmic programming contest. Top performers get fast-tracked interviews.",
        "eligibility": "Anyone 18+.",
        "prizes": "USD 20,000 grand prize, Meta interview pipeline.",
        "source_url": "https://www.facebook.com/codingcompetitions",
        "prep": None,
    },
    {
        "title": "Amazon HackOn",
        "company": "Amazon",
        "company_logo": "https://logo.clearbit.com/amazon.com",
        "region": "India",
        "mode": "Hybrid",
        "status": "Upcoming",
        "tags": ["Hiring", "Hackathon", "ML / Cloud"],
        "start_date": _future(30),
        "end_date": _future(45),
        "registration_deadline": _future(25),
        "registration_link": "https://amazonhackon.com",
        "location": "Online + Bengaluru / Hyderabad",
        "description": "Amazon India's flagship hiring hackathon across ML, Cloud, Mobile and AWS tracks.",
        "eligibility": "Engineering students graduating in 2025 / 2026.",
        "prizes": "PPO + INR 3L grand prize per track.",
        "source_url": "https://amazonhackon.com",
        "prep": None,
    },
    {
        "title": "Microsoft Engage",
        "company": "Microsoft",
        "company_logo": "https://logo.clearbit.com/microsoft.com",
        "region": "India",
        "mode": "Online",
        "status": "Upcoming",
        "tags": ["Mentorship", "Hiring", "Project"],
        "start_date": _future(45),
        "end_date": _future(90),
        "registration_deadline": _future(40),
        "registration_link": "https://microsoft.acehacker.com/engage",
        "location": "Online (India)",
        "description": "4-week mentorship program by Microsoft engineers. Top performers get internship + PPO interviews.",
        "eligibility": "Pre-final year engineering students (India).",
        "prizes": "Internship at Microsoft + PPO fast-track.",
        "source_url": "https://microsoft.acehacker.com/engage",
        "prep": None,
    },
    {
        "title": "Atlassian CodeFest",
        "company": "Atlassian",
        "company_logo": "https://logo.clearbit.com/atlassian.com",
        "region": "International",
        "mode": "Online",
        "status": "Open",
        "tags": ["Hiring", "SDE", "DevOps"],
        "start_date": _future(2),
        "end_date": _future(9),
        "registration_deadline": _future(1),
        "registration_link": "https://www.atlassian.com/company/careers/students",
        "location": "Online (Global)",
        "description": "Atlassian's developer hiring challenge. Coding + project round on Jira / Confluence APIs.",
        "eligibility": "Final year CS students globally.",
        "prizes": "Atlassian SDE offer, swag and AUD 5000 cash.",
        "source_url": "https://www.atlassian.com/company/careers/students",
        "prep": None,
    },
    {
        "title": "Zomato 25",
        "company": "Zomato",
        "company_logo": "https://logo.clearbit.com/zomato.com",
        "region": "India",
        "mode": "Offline",
        "status": "Upcoming",
        "tags": ["Hiring", "Product", "Hackathon"],
        "start_date": _future(50),
        "end_date": _future(52),
        "registration_deadline": _future(45),
        "registration_link": "https://www.zomato.com/careers",
        "location": "Gurgaon (HQ)",
        "description": "Zomato's intense 48-hour onsite hiring hackathon for Product, SDE & Design.",
        "eligibility": "Pre-final / final year students invited via online round.",
        "prizes": "PPO + INR 5L pool prize.",
        "source_url": "https://www.zomato.com/careers",
        "prep": None,
    },
    {
        "title": "Uber HackTag",
        "company": "Uber",
        "company_logo": "https://logo.clearbit.com/uber.com",
        "region": "India",
        "mode": "Hybrid",
        "status": "Upcoming",
        "tags": ["Hiring", "Backend", "Distributed Systems"],
        "start_date": _future(20),
        "end_date": _future(35),
        "registration_deadline": _future(15),
        "registration_link": "https://www.uber.com/us/en/careers/students/",
        "location": "Online + Bengaluru / Hyderabad finals",
        "description": "Uber India hiring hackathon focused on backend, ML and infra problems.",
        "eligibility": "B.Tech / M.Tech CS graduating in 2025.",
        "prizes": "PPO offers + INR 4L prize pool.",
        "source_url": "https://www.uber.com/us/en/careers",
        "prep": None,
    },
    {
        "title": "GitHub Universe Hackathon",
        "company": "GitHub",
        "company_logo": "https://logo.clearbit.com/github.com",
        "region": "International",
        "mode": "Online",
        "status": "Open",
        "tags": ["Open Source", "DevTools", "Global"],
        "start_date": _future(0),
        "end_date": _future(14),
        "registration_deadline": _future(12),
        "registration_link": "https://githubuniverse.com/hackathon",
        "location": "Online (Global)",
        "description": "Build an OSS project using GitHub Copilot, Actions or Codespaces. Win SWAG, cash and interview tracks.",
        "eligibility": "Anyone 18+ with a GitHub account.",
        "prizes": "USD 10,000 + interview fast-track at GitHub.",
        "source_url": "https://githubuniverse.com",
        "prep": None,
    },
    {
        "title": "Razorpay FTX",
        "company": "Razorpay",
        "company_logo": "https://logo.clearbit.com/razorpay.com",
        "region": "India",
        "mode": "Online",
        "status": "Open",
        "tags": ["Hiring", "Fintech", "SDE"],
        "start_date": _future(3),
        "end_date": _future(17),
        "registration_deadline": _future(2),
        "registration_link": "https://razorpay.com/ftx",
        "location": "Online (India)",
        "description": "Razorpay's premier full-time hiring exam for SDE roles. 3-stage coding + system design challenge.",
        "eligibility": "Graduating in 2025, CS / IT / ECE.",
        "prizes": "Razorpay SDE-1 offer + INR 1L bonus.",
        "source_url": "https://razorpay.com/jobs",
        "prep": None,
    },
]
